-- Role for all end users
CREATE ROLE TPCH_END_USERS;

-- Grant SELECT on all TPCH tables to role
GRANT SELECT ON SYSTEM.REGION TO TPCH_END_USERS;
GRANT SELECT ON SYSTEM.NATION TO TPCH_END_USERS;
GRANT SELECT ON SYSTEM.PART TO TPCH_END_USERS;
GRANT SELECT ON SYSTEM.SUPPLIER TO TPCH_END_USERS;
GRANT SELECT ON SYSTEM.PARTSUPP TO TPCH_END_USERS;
GRANT SELECT ON SYSTEM.CUSTOMER TO TPCH_END_USERS;
GRANT SELECT ON SYSTEM.ORDERS TO TPCH_END_USERS;
GRANT SELECT ON SYSTEM.LINEITEM TO TPCH_END_USERS;

-- Create user
CREATE USER TPCH_USER IDENTIFIED BY "tpch123"
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;

-- Allow login
GRANT CREATE SESSION TO TPCH_USER;

-- Assign the role
GRANT TPCH_END_USERS TO TPCH_USER;

-- Table stores which logical role the user has
CREATE TABLE SYSTEM.USER_ROLE_MAP (
    USERNAME  VARCHAR2(30) PRIMARY KEY,
    ROLE_NAME VARCHAR2(30) NOT NULL
);

-- Insert mapping for user
INSERT INTO SYSTEM.USER_ROLE_MAP VALUES ('TPCH_USER', 'TPCH_END_USERS');

CREATE TABLE SYSTEM.USER_CUSTOMER_MAP (
    USERNAME   VARCHAR2(30) PRIMARY KEY,
    CUSTKEY    NUMBER(10) NOT NULL
);

INSERT INTO SYSTEM.USER_CUSTOMER_MAP VALUES ('TPCH_USER', 12345);

CREATE OR REPLACE PACKAGE SYSTEM.TPCH_CTX_PKG AS
  PROCEDURE SET_ROLE_CONTEXT;
END;
/

CREATE OR REPLACE PACKAGE BODY SYSTEM.TPCH_CTX_PKG AS
  PROCEDURE SET_ROLE_CONTEXT IS
    v_role VARCHAR2(30);
  BEGIN
    BEGIN
      SELECT ROLE_NAME
        INTO v_role
        FROM SYSTEM.USER_ROLE_MAP
       WHERE USERNAME = SYS_CONTEXT('USERENV','SESSION_USER')
         AND ROWNUM = 1;

      -- Set application context
      DBMS_SESSION.SET_CONTEXT('TPCH_CTX', 'ROLE', v_role);

    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        DBMS_SESSION.SET_CONTEXT('TPCH_CTX', 'ROLE', NULL);
    END;
  END;
END;
/

CREATE OR REPLACE CONTEXT TPCH_CTX USING SYSTEM.TPCH_CTX_PKG;

CREATE OR REPLACE TRIGGER SYSTEM.TPCH_LOGON_TRG
AFTER LOGON ON DATABASE
BEGIN
  -- Set role context for session; raise exception if no mapping
  SYSTEM.TPCH_CTX_PKG.SET_ROLE_CONTEXT;
END;
/

CREATE OR REPLACE PACKAGE SYSTEM.TPCH_CUSTOMER_CTX_PKG AS
  PROCEDURE SET_CUSTOMER_CONTEXT;
END;
/

CREATE OR REPLACE PACKAGE BODY SYSTEM.TPCH_CUSTOMER_CTX_PKG AS
  PROCEDURE SET_CUSTOMER_CONTEXT IS
    v_cust_key NUMBER(10);
  BEGIN
    BEGIN
      -- Lookup customer key mapped to current session user
      SELECT CUSTKEY
        INTO v_cust_key
        FROM SYSTEM.USER_CUSTOMER_MAP
       WHERE USERNAME = SYS_CONTEXT('USERENV','SESSION_USER')
         AND ROWNUM = 1;

      -- Set the application context for this session
      DBMS_SESSION.SET_CONTEXT('APP_CTX', 'CURRENT_CUSTOMER', v_cust_key);

    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        DBMS_SESSION.SET_CONTEXT('APP_CTX', 'CURRENT_CUSTOMER', NULL);
    END;
  END;
END;
/

CREATE OR REPLACE CONTEXT APP_CTX USING SYSTEM.TPCH_CUSTOMER_CTX_PKG;

CREATE OR REPLACE TRIGGER SYSTEM.TPCH_CUSTOMER_LOGON_TRG
AFTER LOGON ON DATABASE
BEGIN
  -- Set current customer for session
  SYSTEM.TPCH_CUSTOMER_CTX_PKG.SET_CUSTOMER_CONTEXT;
END;
/


